version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      - api_futebol:/var/lib/postgresql

  api_app:
    depends_on:
      - postgresdb
    build:
      dockerfile: Dockerfile
    container_name: api_futebol_app
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ~/.m2:/root/.m2
    stdin_open: true

volumes:
  api_futebol:
